name: HeartEmote
main: io.github.koba.heartemote.HeartEmotePlugin
api-version: 1.20
version: 1.0.3
author: Koba
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib:1.9.22
  - org.jetbrains.kotlin:kotlin-reflect:1.9.22
